Objective:

To become comfortable with NumPy arrays and basic operations.

Like other Python libraries, must be explicitly imported

into a Python script or interactive session to make its

functions and objects accessible.

Python uses namespaces to prevent naming clashes. A

namespace is a container that holds a collection of

identifiers like variable and function names.

Without explicit imports, if two different libraries used

the same function name, they would conflict.

In [4]:
# np is an alias or alternative name.
import numpy as np

In [5]:
# .array() function accepts a list as an argument.
arr1 = np.array([1, 2, 3, 4, 5])

In [7]:
# Arrays in NumPy are instance of the ndarray class.
type(arr1)

numpy.ndarray

In [8]:
type([1, 2, 3, 4, 5])

list

In [47]:
# If the dtype parameter is left out of the function call,
# the default type will be float.

# int, str, and bool are just some of the data types
# can be assigned to the dtype parameter.
matrix1 = np.zeros((2, 3), dtype=bool, order='F')

In [48]:
matrix1

array([[False, False, False],
       [False, False, False]])

In [49]:
type(10.)

float

In [50]:
first_row = matrix1[0, :]

In [29]:
first_row

array([0, 0, 0])

The code demonstrates how the memory layout (C-order vs F-order)

of a NumPy array affects computational performance when performing

operations along different axes.

In [30]:
import time

# Create a large 2D array
shape = (5000, 5000)

# Create a C-order (row-major) array
c_array = np.arange(shape[0] * shape[1], dtype=np.int32).reshape(shape, order='C')

# Create an F-order (column-major) array
f_array = np.arange(shape[0] * shape[1], dtype=np.int32).reshape(shape, order='F')

# Test performance for row-wise sum (fast for C-order)
print("Timing row-wise sum:")
start_time = time.time()
np.sum(c_array, axis=1) # Summing along rows is fast for C-order
print(f"C-order time: {time.time() - start_time:.4f}s")

start_time = time.time()
np.sum(f_array, axis=1) # Summing along rows is slower for F-order
print(f"F-order time: {time.time() - start_time:.4f}s")
print("-" * 20)

# Test performance for column-wise sum (fast for F-order)
print("Timing column-wise sum:")
start_time = time.time()
np.sum(c_array, axis=0) # Summing along columns is slow for C-order
print(f"C-order time: {time.time() - start_time:.4f}s")

start_time = time.time()
np.sum(f_array, axis=0) # Summing along columns is fast for F-order
print(f"F-order time: {time.time() - start_time:.4f}s")

Timing row-wise sum:
C-order time: 0.0934s
F-order time: 0.0817s
--------------------
Timing column-wise sum:
C-order time: 0.0767s
F-order time: 0.0744s


A matrix with three rows and three columns.

In [43]:
matrix2 = np.ones((3, 3))

In [44]:
matrix2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
for i in range(1, 11, 1):
    # Positional argument: 1
    # Keyword argument: end="\n"
    # print(i, end="\n")

    print(i, end=",")

    # print(i)

    # if i != 10:
    #     print(i, end=", ")
    # else:
    #     print(i)

1,2,3,4,5,6,7,8,9,10,

In [66]:
# np.arange(start, stop, step)
arr2 = np.arange(0, 10, 2)

In [67]:
arr2

array([0, 2, 4, 6, 8])