In [1]:
import numpy as np

In [2]:
zeros = np.zeros((3, 4))

In [3]:
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


An identity matrix is one with 1s along its diagnol and <br>
zeros elsewhere.

In [4]:
identity_matrix = np.eye(3)

In [5]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Five evenly spaced values from 0 to 1.

In [6]:
linspace = np.linspace(0, 1, 5)

In [8]:
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


The np.random.rand() function in NumPy is used to generate <br>
random numbers from a uniform distribution over the interval <br>
[0, 1).

numpy.random is the module. <br>
rand() is the function defined inside of the numpy.random module.

In [20]:
from numpy import random as rd

In [13]:
# random = np.random.rand(3, 3)

In [29]:
random = rd.rand(3, 3)

In [30]:
print(random)

[[0.52667007 0.99335759 0.99269852]
 [0.11713166 0.94416776 0.50291702]
 [0.9382625  0.05820482 0.85310301]]


In [34]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]], dtype=float)

In [35]:
data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Only passing the matrix as the argument to the mean() function <br>
will compute the mean for all of the values in the 2D array.

In [46]:
mean_for_all_values = np.mean(data)

In [47]:
print(mean_for_all_values)

5.0


The keyword argument axis=0 specifies that the mean/average <br>
for each column will be calculated.

In [48]:
mean_for_each_column = np.mean(data, axis=0)

In [49]:
print(mean_for_each_column)

[4. 5. 6.]


In [50]:
mean_for_each_row = np.mean(data, axis=1)

In [51]:
print(mean_for_each_row)

[2. 5. 8.]


In [80]:
three_d_ndarray = np.array(
[
    [
        [0, 1], [2, 3]
    ],
    [
        [4, 5], [6, 7]
    ]
], dtype=int)

In [86]:
print(three_d_ndarray)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [87]:
mean_for_each_column = np.mean(three_d_ndarray, axis=0)

In [88]:
print(mean_for_each_column)

[[2. 3.]
 [4. 5.]]


In [89]:
mean_for_each_row = np.mean(three_d_ndarray, axis=1)

In [90]:
print(mean_for_each_row)

[[1. 2.]
 [5. 6.]]


The highest max

In [70]:
mean = np.mean(three_d_ndarray, axis=2)

In [71]:
print(mean)

[[0. 1.]
 [2. 3.]]
