In [3]:
import numpy as np

In [4]:
x = np.array([1, 2, 3])

In [5]:
x

array([1, 2, 3])

Declare a variable y and have it point to the same memory address that x points to.

There is no copy being created in this case.

In [9]:
y = x

Make a deep copy of x and assign it to variable z.

In [10]:
deep_copy_of_x = np.copy(x)

In [11]:
y is x

True

In [12]:
x is y

True

Reveal the memory addresses of x, y, and deep_copy_of_x.

In [16]:
hex(id(x))

'0x7a20a8d5c210'

In [17]:
hex(id(y))

'0x7a20a8d5c210'

In [18]:
hex(id(deep_copy_of_x))

'0x7a20a8041bf0'

In [19]:
x[0] = 10

In [20]:
x

array([10,  2,  3])

In [21]:
y

array([10,  2,  3])

In [22]:
deep_copy_of_x

array([1, 2, 3])