In [3]:
import numpy as np

In [4]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

No new object is created.

a and b are two names for the same ndarray object.

In [6]:
b = a

In [7]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

b is a and a is b return True because ndarrays a and b reference the same memory address.

In [8]:
b is a

True

In [10]:
a is b

True

Element-wise comparison: <br>
Compares each element of ndarray b with the corresponding element in ndarray a.

In [9]:
b == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Update the value stored at the second row and

in the third column.

In [7]:
b[1, 2] = 99

Show the updated multi-dimensional array a.

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

To obtain the memory address of an object in Python,

use the built-in id() function.

Notice how the memory addresses for matrices a and b are

the same.

In [10]:
id(a)

130336162952176

In [12]:
print(id(b))

130336162952176


The view method creates a new array object that looks at the same data.

The .view() method creates a new array object that views the same data
as the original array.

In [13]:
c = a.view()

In [14]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [15]:
c is a

False

Object c does not have the same memory address as a

because unlike object b, c is a new ndarray object.

In [17]:
id(a) == id(c)

False

In [1]:
type(c)

NameError: name 'c' is not defined

In [19]:
c[0, 0] = 100

In [22]:
c

array([[100,   1,   2,   3],
       [  4,   5,  99,   7],
       [  8,   9,  10,  11]])

In [20]:
a

array([[100,   1,   2,   3],
       [  4,   5,  99,   7],
       [  8,   9,  10,  11]])

Python's built-in hex() function converts memory addresses, <br>
which are represented internally as large integers, into a more <br>
compact and human-readable format.

In [26]:
hex(id(a))

'0x768a40b1b3f0'

In [27]:
hex(a.ctypes.data)

'0x38f3b6d0'

Why is being aware of the memory address of data important?

Answer: <br>
Being aware of the memory address of the data is important because <br>
if two arrays share the same underlying memory (as with views), modifying <br>
one will also modify the other.

If we are unaware that b points to the same memory as a, we might <br>
unintentionally overwrite or lose the original data when modifying b.

Is a view the same as a shallow copy?

Answer: <br>
A view is similar to a shallow copy, but unlike a typical shallow copy, it <br>
doesn't even copy references, it directly shares the same underlying <br>
memory buffer.