In [1]:
import numpy as np

In [2]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

No new object is created.

a and b are two names for the same ndarray object.

In [4]:
b = a

In [5]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b is a

True

Update the value stored at the second row and

in the third column.

In [7]:
b[1, 2] = 99

Show the updated multi-dimensional array a.

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

To obtain the memory address of an object in Python,

use the built-in id() function.

Notice how the memory addresses for matrices a and b are

the same.

In [10]:
id(a)

130336162952176

In [12]:
print(id(b))

130336162952176


The view method creates a new array object that looks at the same data.

The .view() method creates a new array object that views the same data
as the original array.

In [13]:
c = a.view()

In [14]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [15]:
c is a

False

Object c does not have the same memory address as a

because unlike object b, c is a new ndarray object.

In [17]:
id(a) == id(c)

False

In [18]:
type(c)

numpy.ndarray

In [19]:
c[0, 0] = 100

In [22]:
c

array([[100,   1,   2,   3],
       [  4,   5,  99,   7],
       [  8,   9,  10,  11]])

In [20]:
a

array([[100,   1,   2,   3],
       [  4,   5,  99,   7],
       [  8,   9,  10,  11]])

Python's built-in hex() function converts memory addresses, <br>
which are represented internally as large integers, into a more <br>
compact and human-readable format for memory addresses.

In [26]:
hex(id(a))

'0x768a40b1b3f0'

In [27]:
hex(a.ctypes.data)

'0x38f3b6d0'