In [1]:
# Import the NumPy library for numerical operations.
import numpy as np

In [2]:
# Create a 1D array with values from 10 to 18 (inclusive).
m = np.arange(10, 19)

In [3]:
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [4]:
# Check the type of the array 'm' (it should be <class 'numpy.ndarray'>).
type(m)

numpy.ndarray

Reshaping the ndarray so that it has three rows and three columns.

In [5]:
# Reshape 'm' into a 3x3 matrix (note: original array has 9 elements).
m.reshape(3, 3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
# Find the minimum value of the matrix.
min = matrix.min()

In [12]:
# Print the minimum value of the matrix.
print(f"{min} is the minimum of the entire matrix.".format(m.min()))

10 is the minimum of the entire matrix.


The .mean() method can be invoked on Numpy ndarrays to compute the mean/average.

In [17]:
# Print the mean (average) of the array 'm' rounded to 2 decimal places.
print(f"The mean/average of matrix 'm' is {m.mean():.2f}.")

The mean/average of matrix 'm' is 14.00.


The .std() method can be invoked on Numpy ndarrays to compute the standard deviation.

In [16]:
print(f"The standard deviation of matrix 'm' is {m.std():.2f}.")

The standard deviation of matrix 'm' is 2.58.


The .var() method can be invoked on Numpy ndarrays to compute the variance.

In [18]:
print(f"The variance of matrix 'm' is {m.var():.2f}.")

The variance of matrix 'm' is 6.67.


In [23]:
# Create an array of 100 random values between 0 and 100 (uniform distribution).
uniform_array = np.random.uniform(low=0, high=100, size=100)

In [24]:
uniform_array

array([94.97471149, 80.3380134 , 67.07459609, 53.18497784, 43.2450328 ,
       72.74824604, 51.43598261, 12.34273357, 31.24030129, 75.25166159,
       68.91370694, 93.28318701, 44.18327875, 51.71839252, 88.3979375 ,
        2.68052874, 77.59729833, 80.3883764 , 78.96062199, 58.1417425 ,
       98.55391206, 13.8750152 ,  0.55317823, 67.41004617, 49.0592754 ,
       15.32289   , 60.07674668,  3.95413973, 16.4322904 , 29.68275791,
       98.79162764, 16.48889912, 94.76744978, 26.09709479, 87.95756225,
       47.59082003, 75.24473856, 24.57027502, 77.20091604, 46.42164987,
       81.45878385, 65.68879057, 82.73524298, 58.11049148,  3.4092386 ,
       23.81172485, 11.36275541,  4.141211  , 98.44389615, 47.27572191,
       98.22214821, 72.3429167 ,  1.5171656 , 51.57282227, 56.76302194,
       14.62264073, 51.20383477,  4.33374436, 44.93140155, 64.56400838,
       83.85233   , 62.84213253, 91.34288654, 38.89794137, 98.50607136,
       61.35362518, 67.39319052,  3.32751752, 27.91736091, 95.92

uniform_array is the ndarray of data.

95 represents the percentile.

In [25]:
# Compute the 95th percentile of the uniform array.
p95 = np.percentile(uniform_array, 95)

In [26]:
p95

np.float64(98.23323560465145)

Only see values that are in the top five percent.

In [37]:
# Select values that are in the top 5% of the uniform array.
top_5_percent = uniform_array[uniform_array > p95]

In [38]:
# Check the type of the top 5% array (it will be a NumPy ndarray).
type(top_5_percent)

numpy.ndarray

In [40]:
# Round the top 5% values to 2 decimal places.
top_5_percent = np.round(top_5_percent, 2)

In [41]:
print(f"Top 5% of values: {top_5_percent}")

Top 5% of values: [98.55 98.79 98.44 98.51 99.4 ]


In [56]:
# These are 1D ndarrays which Numpy treats as vectors for most operations.
ndarray_a = np.array([1, 2, 3, 4, 5])
ndarray_b = np.array([10, 20, 30, 40, 50])

The .prod() method computes 1 * 2* 3 * 4 * 5 in this context.

In [57]:
ndarray_a.prod()

np.int64(120)

In this context, the dot() function performs the following: <br>
1 * 10 + 2 * 20 + 3 * 30 + 4 * 40 + 5 * 50

In [ ]:
dot_product1 = np.dot(ndarray_a, ndarray_b)

In [43]:
dot_product1

np.int64(550)

In [44]:
dot_product2 = ndarray_a @ ndarray_b

In [45]:
dot_product2

np.int64(550)

In [46]:
# Compute element-wise multiplication of 'a' and 'b'.
element_wise = ndarray_a * ndarray_b

element_wise

array([ 10,  40,  90, 160, 250])

The ndarray class has a method named .sum() which will simply compute the sum <br>
of all numbers.

In [47]:
ndarray_a.sum()

np.int64(15)

In [51]:
# Get the number of dimensions of 'a' (should be 1 for 1D array).
ndarray_a.ndim

1

The ndarray class has a .reshape(no_of_rows, no_of_columns) method.

In [54]:
ndarray_a = ndarray_a.reshape(5, 1)

In [55]:
# Check the number of dimensions again (should now be 2).
ndarray_a.ndim

2

In [59]:
# Compute the cumulative sum of 'a' (running total).
ndarray_a.cumsum()

array([ 1,  3,  6, 10, 15])

In [61]:
# Generate the Fibonacci sequence up to N terms.
N = 10

# Initialise the Fibonacci sequence with the first two numbers.
fib = np.array([0, 1])

for i in range(2, N):
    # Compute the next Fibonacci number as the sum of the last two.
    next_value = fib[-1] + fib[-2]

    # Append the next value to the sequence.
    fib = np.append(fib, next_value)

# Print the generated Fibonacci sequence.
print(fib)

[ 0  1  1  2  3  5  8 13 21 34]
