In [2]:
import numpy as np

In [9]:
np.arange(0, 6, 1)

array([0, 1, 2, 3, 4, 5])

The following produces the same ndarray as:

a = np.arange(0, 6, 1)

In [7]:
a = np.arange(6)

In [8]:
print(a)

[0 1 2 3 4 5]


reshape(no_of_rows, no_of_columns)

In [3]:
b = np.arange(12).reshape(4, 3)

In [4]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
b = np.arange(12).reshape(3, 4)

In [6]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

reshape(number_of_blocks, number_of_rows, number_of_columns)

2 → number of “blocks” (outermost dimension)

3 → number of rows (middle dimension)

4 → number of columns (innermost dimension)

reshape(dim1, dim2, dim3)

changes the array to have a shape of (dim1, dim2, dim3),
where: <br>
dim1 → size of the first (outermost) dimension

dim2 → size of the second dimension (rows)

dim3 → size of the third dimension (columns)

Total elements: 2 × 3 × 4 = 24

In [10]:
c = np.arange(24).reshape(2, 3, 4)

In [11]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])