In [1]:
import numpy as np

In [2]:
ndarray1 = np.arange(0, 6, 1)

In [4]:
ndarray1

array([0, 1, 2, 3, 4, 5])

Reveal the memory address of ndarray1.

In [16]:
hex(id(ndarray1))

'0x7d7330142e50'

In [5]:
ndarray_reshaped = ndarray1.reshape(2, 3)

In [6]:
ndarray_reshaped

array([[0, 1, 2],
       [3, 4, 5]])

Reveal the memory address of ndarray_reshaped.

In [18]:
hex(id(ndarray_reshaped))

'0x7d7308768210'

reshape() and resize() can be contrasted by the fact that reshape() returns <br>
a new view object (shallow copy) of the resize() returns None.

Therefore, after invoking the resize() method on an ndarray object, <br>
the result doesn't need to be assigned to be visualised.

In [11]:
ndarray1.resize(6, 1)

In [12]:
ndarray1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

Reveal the memory address of ndarray1.

In [17]:
hex(id(ndarray1))

'0x7d7330142e50'